<?php

echo "    <nav class=\"pushy pushy-left \"data-focus=\"#first-link\">\n";
echo "            <div class=\"pushy-content\">\n";
echo "                <ul>\n";
echo "                   \n";
echo "                   	<li class=\"pushy-link\"><a href=\"home.php\">Dashboard</a></li>\n";
echo "                   	<li class=\"pushy-link\"><a href=\"client_list.php\">Client List</a></li>\n";
echo "                    <li class=\"pushy-link\"><a href=\"intake_forms.php\">Intake Forms</a></li>\n";
echo "                    <li class=\"pushy-link\"><a href=\"informed_consent.php\">Informed Consent</a></li>    \n";
echo "                    	\n";
echo "                    <li class=\"pushy-submenu\">\n";
echo "                        <button id=\"first-link\">Session Notes</button>\n";
echo "                        <ul>\n";
echo "                        <li class=\"pushy-link\"><a href=\"children_progress.php\">Children Progress Notes</a></li>\n";
echo "                    	<li class=\"pushy-link\"><a href=\"soap.php\">STEP Notes</a></li>\n";
echo "                    	<li class=\"pushy-link\"><a href=\"soap4.php\">SOAP Notes</a></li>    \n";
echo "                    	<li class=\"pushy-link\"><a href=\"non_counseling.php\">Non-Counseling Notes</a></li>\n";
echo "                    	<li class=\"pushy-link\"><a href=\"termination_summary.php\">Termination Summary</a></li>    \n";
echo "                    	</ul>\n";
echo "                    </li>\n";
echo "                    \n";
echo "                    <li class=\"pushy-submenu\">\n";
echo "                        <button id=\"first-link\">Treatment Plans</button>\n";
echo "                        <ul>\n";
echo "                        <li class=\"pushy-link\"><a href=\"treatment_plan.php\">Treatment Plans</a></li>\n";
echo "                    	<li class=\"pushy-link\"><a href=\"treatment_update.php\">Weekly Updates</a></li>      \n";
echo "                    	</ul>\n";
echo "                    </li>\n";
echo "                    \n";
//echo "                    <li class=\"pushy-link\"><a href=\"activity_sheets.php\">Activity Sheets</a></li>\n";
//echo "                    \n";
echo "                    <li class=\"pushy-submenu\">\n";
echo "                        <button id=\"first-link\">Finance & Bills</button>\n";
echo "                        <ul>\n";
echo "                    	<li class=\"pushy-link\"><a href=\"service_and_charge.php\">Service & Charge</a></li>    \n";
echo "                        <li class=\"pushy-link\"><a href=\"superbills.php\">Superbill</a></li>\n";
echo "                    	<li class=\"pushy-link\"><a href=\"invoice.php\">Client Invoices</a></li>    \n";
echo "                    	<li class=\"pushy-link\"><a href=\"expense.php\">Expenses</a></li>    \n";
echo "                    	</ul>\n";
echo "                    </li>\n";
echo "                    \n";
echo "                    <br />\n";
echo "                    <br />\n";
echo "                    <br />\n";
echo "                    <br />\n";
echo "                    <li class=\"pushy-link\"><a href=\"dashboard_setting.php\">Dashboard Setting</a></li>\n";
echo "                    \n";
echo "                    <li class=\"pushy-link\"><a href=\"logout.php\">Log Out</a></li>\n";
echo "                    \n";
echo "                </ul>\n";
echo "            </div>\n";
echo "        </nav>";

?>